# 端口
server:
  port: 8761

spring:
  application:
    name: cloud-eureka-server
  security:
    user:
      name: root
      password: 123456

# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: eureka8761.com
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检查服务
    fetch-registry: false
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka8762.com:8762/eureka,http://${spring.security.user.name}:${spring.security.user.password}@eureka8763.com:8763/eureka